  version: 2.1
  jobs:
    build:
      docker:
        - image: circleci/node:12.6
      steps: # a collection of executable commands
        - restore_cache:
            name: Restore Yarn Package Cache
            keys:
              - yarn-packages-{{ checksum "yarn.lock" }}
        - run:
            name: Install Dependencies
            command: yarn install --frozen-lockfile
        - run:
            name: Build
            command: yarn run build
        - save_cache:
            name: Save Yarn Package Cache
            key: yarn-packages-{{ checksum "yarn.lock" }}
            paths:
              - ~/.cache/yarn
