version: 2.1

general:
  branches:
    only:
      - master

jobs:
  build:
    docker:
      - image: circleci/node:12.6
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
      - run:
          name: Build Applications
          command: yarn run build
      - run:
          name: Deploy Applications
          command: yarn run deploy:production
  test:
    docker:
      - image: circleci/node:12.6
    steps:
      - checkout
      - run:
          name: Test
          command: yarn run test
  deploy:
    docker:
      - image: circleci/node:12.6
    steps:
      - checkout
      - run:
          name: Deploy
          command: yarn run deploy

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          context: Escalade
      - test:
          context: Escalade
          requires:
            - build
      - deploy:
          # filters:
          #   branches:
          #     only: master
          context: Escalade
          requires:
            - test
