version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.6

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
      - run:
          name: Build Applications
          command: yarn run build
      - persist_to_workspace:
          root: ~/repo
          paths: .
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Test
          command: yarn run test
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Deploy Applications
          command: yarn run deploy:production

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          context: Escalade
      - test:
          context: Escalade
          requires:
            - build
      - deploy:
          # filters:
          #   branches:
          #     only: master
          context: Escalade
          requires:
            - test
