backend:
  name: git-gateway
  accept_roles:
    - admin

media_folder: static/uploads
public_folder: /uploads

collections:
  - label: Pages
    name: pages
    files:
      - label: Home
        name: index
        file: src/markdown/index.md
        fields:
          - label: Body
            name: body
            widget: markdown
          - label: Header Image
            name: headerImage
            widget: image
      - label: Contact
        name: contact
        file: src/markdown/contact.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
      - label: Privacy Policy
        name: privacy-policy
        file: src/markdown/privacy-policy.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Address
            name: address
            widget: text
          - label: Email
            name: email
            widget: string
          - label: Body
            name: body
            widget: markdown
      - label: Page Not Found
        name: '404'
        file: src/markdown/404.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
  - label: Blog
    name: blog
    folder: src/markdown/blog
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: date
      - label: Tags
        name: tags
        widget: list
      - label: Path
        name: path
        widget: string
        pattern: ["^[a-z0-9_-]+$", "Must contain only lowercase characters and hyphens"]
        hint: The URL to the page. Must contain only lowercase characters and hyphens.
        required: false
      - label: Body
        name: body
        widget: markdown
  - label: Settings
    name: settings
    files:
      - label: Site Settings
        name: site
        file: src/markdown/site.md
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Site Settings
          - label: Site Title
            name: siteTitle
            widget: text
          - label: Site Description
            name: siteDescription
            widget: text
          - label: Maximum Posts Per Page
            name: postsPerPage
            widget: number
            valueType: int
            min: 1