label: Products
name: products
folder: src/markdown/products
create: true
editor:
  preview: false
fields:
  - label: Name
    name: title
    widget: string
  - label: ID
    name: id
    widget: string
    pattern:
      - ^[a-zA-Z0-9_-]+$
      - Must contain only alphanumeric characters and hyphens
    hint: Must contain only alphanumeric characters and hyphens
  - label: Category
    name: category
    widget: relation
    collection: categories
    searchFields:
      - id
      - title
    valueField: id
    displayFields:
      - title
  - label: Color
    name: color
    widget: string
  - label: Price
    name: price
    widget: currency
    required: false
    default: 0
  - label: Body
    name: body
    widget: markdown
  - label: Images
    name: images
    widget: list
    field:
      label: Image
      name: image
      widget: image
  - label: Order
    name: order
    widget: number
    valueType: int
    default: 1
    hint: Products on the site are ordered from lowest to highest number
  - label: Published
    name: published
    widget: boolean
    default: true
  - label: Variants
    name: variants
    widget: list
    required: false
    fields:
      - label: Color
        name: color
        widget: string
      - label: ID
        name: id
        widget: string
        pattern:
          - ^[a-zA-Z0-9_-]+$
          - Must contain only alphanumeric characters and hyphens