label: Settings
name: settings
editor:
  preview: false
files:
  - label: Site Settings
    name: site
    file: src/markdown/settings/site.md
    fields:
      - label: Title
        name: title
        widget: hidden
        default: Site Settings
      - label: Site Title
        name: siteTitle
        widget: string
      - label: Site Description
        name: siteDescription
        widget: text
      - label: Maximum Posts Per Page
        name: postsPerPage
        widget: number
        valueType: int
        min: 1